// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: api/proto/a2a.proto

package a2apb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendMessageRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TaskId            string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ContextId         string                 `protobuf:"bytes,2,opt,name=context_id,json=contextId,proto3" json:"context_id,omitempty"`
	Message           *Message               `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	ReturnImmediately bool                   `protobuf:"varint,4,opt,name=return_immediately,json=returnImmediately,proto3" json:"return_immediately,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_api_proto_a2a_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_a2a_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_a2a_proto_rawDescGZIP(), []int{0}
}

func (x *SendMessageRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *SendMessageRequest) GetContextId() string {
	if x != nil {
		return x.ContextId
	}
	return ""
}

func (x *SendMessageRequest) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *SendMessageRequest) GetReturnImmediately() bool {
	if x != nil {
		return x.ReturnImmediately
	}
	return false
}

type SendMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	mi := &file_api_proto_a2a_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_a2a_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_a2a_proto_rawDescGZIP(), []int{1}
}

func (x *SendMessageResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type GetTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_api_proto_a2a_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_a2a_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_a2a_proto_rawDescGZIP(), []int{2}
}

func (x *GetTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type StreamTaskEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamTaskEventsRequest) Reset() {
	*x = StreamTaskEventsRequest{}
	mi := &file_api_proto_a2a_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamTaskEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamTaskEventsRequest) ProtoMessage() {}

func (x *StreamTaskEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_a2a_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamTaskEventsRequest.ProtoReflect.Descriptor instead.
func (*StreamTaskEventsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_a2a_proto_rawDescGZIP(), []int{3}
}

func (x *StreamTaskEventsRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"` // user, assistant, system, tool
	Parts         []*Part                `protobuf:"bytes,2,rep,name=parts,proto3" json:"parts,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_api_proto_a2a_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_a2a_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_api_proto_a2a_proto_rawDescGZIP(), []int{4}
}

func (x *Message) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Message) GetParts() []*Part {
	if x != nil {
		return x.Parts
	}
	return nil
}

func (x *Message) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type Part struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Content:
	//
	//	*Part_Text
	//	*Part_ToolCall
	//	*Part_ToolResult
	Content       isPart_Content `protobuf_oneof:"content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Part) Reset() {
	*x = Part{}
	mi := &file_api_proto_a2a_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Part) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Part) ProtoMessage() {}

func (x *Part) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_a2a_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Part.ProtoReflect.Descriptor instead.
func (*Part) Descriptor() ([]byte, []int) {
	return file_api_proto_a2a_proto_rawDescGZIP(), []int{5}
}

func (x *Part) GetContent() isPart_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Part) GetText() string {
	if x != nil {
		if x, ok := x.Content.(*Part_Text); ok {
			return x.Text
		}
	}
	return ""
}

func (x *Part) GetToolCall() *ToolCall {
	if x != nil {
		if x, ok := x.Content.(*Part_ToolCall); ok {
			return x.ToolCall
		}
	}
	return nil
}

func (x *Part) GetToolResult() *ToolResult {
	if x != nil {
		if x, ok := x.Content.(*Part_ToolResult); ok {
			return x.ToolResult
		}
	}
	return nil
}

type isPart_Content interface {
	isPart_Content()
}

type Part_Text struct {
	Text string `protobuf:"bytes,1,opt,name=text,proto3,oneof"`
}

type Part_ToolCall struct {
	ToolCall *ToolCall `protobuf:"bytes,2,opt,name=tool_call,json=toolCall,proto3,oneof"`
}

type Part_ToolResult struct {
	ToolResult *ToolResult `protobuf:"bytes,3,opt,name=tool_result,json=toolResult,proto3,oneof"`
}

func (*Part_Text) isPart_Content() {}

func (*Part_ToolCall) isPart_Content() {}

func (*Part_ToolResult) isPart_Content() {}

type ToolCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	ToolName      string                 `protobuf:"bytes,2,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	Arguments     *structpb.Struct       `protobuf:"bytes,3,opt,name=arguments,proto3" json:"arguments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCall) Reset() {
	*x = ToolCall{}
	mi := &file_api_proto_a2a_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCall) ProtoMessage() {}

func (x *ToolCall) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_a2a_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCall.ProtoReflect.Descriptor instead.
func (*ToolCall) Descriptor() ([]byte, []int) {
	return file_api_proto_a2a_proto_rawDescGZIP(), []int{6}
}

func (x *ToolCall) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *ToolCall) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ToolCall) GetArguments() *structpb.Struct {
	if x != nil {
		return x.Arguments
	}
	return nil
}

type ToolResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	Result        string                 `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolResult) Reset() {
	*x = ToolResult{}
	mi := &file_api_proto_a2a_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolResult) ProtoMessage() {}

func (x *ToolResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_a2a_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolResult.ProtoReflect.Descriptor instead.
func (*ToolResult) Descriptor() ([]byte, []int) {
	return file_api_proto_a2a_proto_rawDescGZIP(), []int{7}
}

func (x *ToolResult) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *ToolResult) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ContextId     string                 `protobuf:"bytes,2,opt,name=context_id,json=contextId,proto3" json:"context_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Status        *TaskStatus            `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	History       []*Message             `protobuf:"bytes,5,rep,name=history,proto3" json:"history,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_api_proto_a2a_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_a2a_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_api_proto_a2a_proto_rawDescGZIP(), []int{8}
}

func (x *Task) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Task) GetContextId() string {
	if x != nil {
		return x.ContextId
	}
	return ""
}

func (x *Task) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Task) GetStatus() *TaskStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *Task) GetHistory() []*Message {
	if x != nil {
		return x.History
	}
	return nil
}

func (x *Task) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Task) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type TaskStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"` // submitted, working, input_required, completed, failed
	Detail        string                 `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskStatus) Reset() {
	*x = TaskStatus{}
	mi := &file_api_proto_a2a_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskStatus) ProtoMessage() {}

func (x *TaskStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_a2a_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskStatus.ProtoReflect.Descriptor instead.
func (*TaskStatus) Descriptor() ([]byte, []int) {
	return file_api_proto_a2a_proto_rawDescGZIP(), []int{9}
}

func (x *TaskStatus) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *TaskStatus) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *TaskStatus) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type TaskEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Data          *structpb.Struct       `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskEvent) Reset() {
	*x = TaskEvent{}
	mi := &file_api_proto_a2a_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskEvent) ProtoMessage() {}

func (x *TaskEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_a2a_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskEvent.ProtoReflect.Descriptor instead.
func (*TaskEvent) Descriptor() ([]byte, []int) {
	return file_api_proto_a2a_proto_rawDescGZIP(), []int{10}
}

func (x *TaskEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TaskEvent) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskEvent) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *TaskEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_api_proto_a2a_proto protoreflect.FileDescriptor

const file_api_proto_a2a_proto_rawDesc = "" +
	"\n" +
	"\x13api/proto/a2a.proto\x12\x10fluxgraph.a2a.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xb0\x01\n" +
	"\x12SendMessageRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"context_id\x18\x02 \x01(\tR\tcontextId\x123\n" +
	"\amessage\x18\x03 \x01(\v2\x19.fluxgraph.a2a.v1.MessageR\amessage\x12-\n" +
	"\x12return_immediately\x18\x04 \x01(\bR\x11returnImmediately\"A\n" +
	"\x13SendMessageResponse\x12*\n" +
	"\x04task\x18\x01 \x01(\v2\x16.fluxgraph.a2a.v1.TaskR\x04task\")\n" +
	"\x0eGetTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"2\n" +
	"\x17StreamTaskEventsRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"\x86\x01\n" +
	"\aMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12,\n" +
	"\x05parts\x18\x02 \x03(\v2\x16.fluxgraph.a2a.v1.PartR\x05parts\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xa3\x01\n" +
	"\x04Part\x12\x14\n" +
	"\x04text\x18\x01 \x01(\tH\x00R\x04text\x129\n" +
	"\ttool_call\x18\x02 \x01(\v2\x1a.fluxgraph.a2a.v1.ToolCallH\x00R\btoolCall\x12?\n" +
	"\vtool_result\x18\x03 \x01(\v2\x1c.fluxgraph.a2a.v1.ToolResultH\x00R\n" +
	"toolResultB\t\n" +
	"\acontent\"w\n" +
	"\bToolCall\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x1b\n" +
	"\ttool_name\x18\x02 \x01(\tR\btoolName\x125\n" +
	"\targuments\x18\x03 \x01(\v2\x17.google.protobuf.StructR\targuments\"=\n" +
	"\n" +
	"ToolResult\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x16\n" +
	"\x06result\x18\x02 \x01(\tR\x06result\"\xb3\x02\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"context_id\x18\x02 \x01(\tR\tcontextId\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x124\n" +
	"\x06status\x18\x04 \x01(\v2\x1c.fluxgraph.a2a.v1.TaskStatusR\x06status\x123\n" +
	"\ahistory\x18\x05 \x03(\v2\x19.fluxgraph.a2a.v1.MessageR\ahistory\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"t\n" +
	"\n" +
	"TaskStatus\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\x9f\x01\n" +
	"\tTaskEvent\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12+\n" +
	"\x04data\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x04data\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp2\x8d\x02\n" +
	"\fAgentService\x12Z\n" +
	"\vSendMessage\x12$.fluxgraph.a2a.v1.SendMessageRequest\x1a%.fluxgraph.a2a.v1.SendMessageResponse\x12C\n" +
	"\aGetTask\x12 .fluxgraph.a2a.v1.GetTaskRequest\x1a\x16.fluxgraph.a2a.v1.Task\x12\\\n" +
	"\x10StreamTaskEvents\x12).fluxgraph.a2a.v1.StreamTaskEventsRequest\x1a\x1b.fluxgraph.a2a.v1.TaskEvent0\x01B4Z2github.com/FluxGraph/fluxgraph/api/proto/a2a;a2apbb\x06proto3"

var (
	file_api_proto_a2a_proto_rawDescOnce sync.Once
	file_api_proto_a2a_proto_rawDescData []byte
)

func file_api_proto_a2a_proto_rawDescGZIP() []byte {
	file_api_proto_a2a_proto_rawDescOnce.Do(func() {
		file_api_proto_a2a_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_a2a_proto_rawDesc), len(file_api_proto_a2a_proto_rawDesc)))
	})
	return file_api_proto_a2a_proto_rawDescData
}

var file_api_proto_a2a_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_proto_a2a_proto_goTypes = []any{
	(*SendMessageRequest)(nil),      // 0: fluxgraph.a2a.v1.SendMessageRequest
	(*SendMessageResponse)(nil),     // 1: fluxgraph.a2a.v1.SendMessageResponse
	(*GetTaskRequest)(nil),          // 2: fluxgraph.a2a.v1.GetTaskRequest
	(*StreamTaskEventsRequest)(nil), // 3: fluxgraph.a2a.v1.StreamTaskEventsRequest
	(*Message)(nil),                 // 4: fluxgraph.a2a.v1.Message
	(*Part)(nil),                    // 5: fluxgraph.a2a.v1.Part
	(*ToolCall)(nil),                // 6: fluxgraph.a2a.v1.ToolCall
	(*ToolResult)(nil),              // 7: fluxgraph.a2a.v1.ToolResult
	(*Task)(nil),                    // 8: fluxgraph.a2a.v1.Task
	(*TaskStatus)(nil),              // 9: fluxgraph.a2a.v1.TaskStatus
	(*TaskEvent)(nil),               // 10: fluxgraph.a2a.v1.TaskEvent
	(*timestamppb.Timestamp)(nil),   // 11: google.protobuf.Timestamp
	(*structpb.Struct)(nil),         // 12: google.protobuf.Struct
}
var file_api_proto_a2a_proto_depIdxs = []int32{
	4,  // 0: fluxgraph.a2a.v1.SendMessageRequest.message:type_name -> fluxgraph.a2a.v1.Message
	8,  // 1: fluxgraph.a2a.v1.SendMessageResponse.task:type_name -> fluxgraph.a2a.v1.Task
	5,  // 2: fluxgraph.a2a.v1.Message.parts:type_name -> fluxgraph.a2a.v1.Part
	11, // 3: fluxgraph.a2a.v1.Message.created_at:type_name -> google.protobuf.Timestamp
	6,  // 4: fluxgraph.a2a.v1.Part.tool_call:type_name -> fluxgraph.a2a.v1.ToolCall
	7,  // 5: fluxgraph.a2a.v1.Part.tool_result:type_name -> fluxgraph.a2a.v1.ToolResult
	12, // 6: fluxgraph.a2a.v1.ToolCall.arguments:type_name -> google.protobuf.Struct
	9,  // 7: fluxgraph.a2a.v1.Task.status:type_name -> fluxgraph.a2a.v1.TaskStatus
	4,  // 8: fluxgraph.a2a.v1.Task.history:type_name -> fluxgraph.a2a.v1.Message
	11, // 9: fluxgraph.a2a.v1.Task.created_at:type_name -> google.protobuf.Timestamp
	11, // 10: fluxgraph.a2a.v1.Task.updated_at:type_name -> google.protobuf.Timestamp
	11, // 11: fluxgraph.a2a.v1.TaskStatus.timestamp:type_name -> google.protobuf.Timestamp
	12, // 12: fluxgraph.a2a.v1.TaskEvent.data:type_name -> google.protobuf.Struct
	11, // 13: fluxgraph.a2a.v1.TaskEvent.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 14: fluxgraph.a2a.v1.AgentService.SendMessage:input_type -> fluxgraph.a2a.v1.SendMessageRequest
	2,  // 15: fluxgraph.a2a.v1.AgentService.GetTask:input_type -> fluxgraph.a2a.v1.GetTaskRequest
	3,  // 16: fluxgraph.a2a.v1.AgentService.StreamTaskEvents:input_type -> fluxgraph.a2a.v1.StreamTaskEventsRequest
	1,  // 17: fluxgraph.a2a.v1.AgentService.SendMessage:output_type -> fluxgraph.a2a.v1.SendMessageResponse
	8,  // 18: fluxgraph.a2a.v1.AgentService.GetTask:output_type -> fluxgraph.a2a.v1.Task
	10, // 19: fluxgraph.a2a.v1.AgentService.StreamTaskEvents:output_type -> fluxgraph.a2a.v1.TaskEvent
	17, // [17:20] is the sub-list for method output_type
	14, // [14:17] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_api_proto_a2a_proto_init() }
func file_api_proto_a2a_proto_init() {
	if File_api_proto_a2a_proto != nil {
		return
	}
	file_api_proto_a2a_proto_msgTypes[5].OneofWrappers = []any{
		(*Part_Text)(nil),
		(*Part_ToolCall)(nil),
		(*Part_ToolResult)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_a2a_proto_rawDesc), len(file_api_proto_a2a_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_a2a_proto_goTypes,
		DependencyIndexes: file_api_proto_a2a_proto_depIdxs,
		MessageInfos:      file_api_proto_a2a_proto_msgTypes,
	}.Build()
	File_api_proto_a2a_proto = out.File
	file_api_proto_a2a_proto_goTypes = nil
	file_api_proto_a2a_proto_depIdxs = nil
}
